enum connected_camera_mode
{
	CC_EDGE_DETECTION_MODE = 121,
	CC_DRAW_MODE = 112,
	CC_BLACK_AND_WHITE_WITH_GRAY_MODE = 103,
	CC_BLACK_AND_WHITE_WITH_RGB_MODE = 97,
	CC_PAINTING_MODE = 99,
	CC_GRAY_AND_WHITE_MODE = 119,
	CC_NEGATIVE_OR_INVERTED_MODE = 105,
	CC_HUE_SATURATION_LIGHTNESS_MODE = 104,
	CC_ORDINARY_MODE = 111
};
